claim/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "claim"

urlpatterns = [
    path('', views.Claim.as_view(), name="claim"),
    path('<username>/', views.ClaimUser.as_view(), name="menu"),
    path('<username>/email/', views.ClaimEmail.as_view(), name="email"),
    path('<username>/login/', views.ClaimLogin.as_view(), name="login"),
    path('<username>/fpr/', views.ClaimFingerprint.as_view(), name="fpr"),
    path('<username>/email/verify', views.ClaimEmailVerify.as_view(), name="verify_email"),
    path('<username>/unclaim/', views.UnclaimMenu.as_view(), name="unclaim_menu"),
    path('<username>/unclaim/<int:ident>/', views.Unclaim.as_view(), name="unclaim"),
    # path('<name>/unclaim/', views.Unclaim.as_view(), name="unclaim"),
]

dc/urls.py
from __future__ import annotations
from django.urls import include, path
from django.views.generic import TemplateView
import django.conf.urls
from contributors import views as cviews
import dclayout.views as dcviews
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'contributors', cviews.ContributorViewSet, "contributors")
router.register(r'identifiers', cviews.IdentifierViewSet, "identifiers")

django.conf.urls.handler403 = dcviews.Error403.as_view()
django.conf.urls.handler404 = dcviews.Error404.as_view()
django.conf.urls.handler500 = dcviews.Error500.as_view()


urlpatterns = [
    path('', cviews.Contributors.as_view(), name="contributors"),
    path('license/', TemplateView.as_view(template_name='license.html'), name="root_license"),
    path('about/privacy/', TemplateView.as_view(template_name='privacy.html'), name="root_privacy"),
    path('admin/', admin.site.urls),
    path('contributors/', include('contributors.urls')),
    path('contributor/', include('contributor.urls')),
    path('source/', include("sources.urls")),
    path('mia/', include("mia.urls")),
    path('importer/', include("importer.urls")),
    path('claim/', include("claim.urls")),
    path('api/', include(router.urls)),
    path('deploy/', include("deploy.urls")),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),
]

claim/models.py
from django.db import models

# Create your models here.

claim/forms.py
from __future__ import annotations
from django.utils.translation import gettext_lazy as _
from django import forms
from dc.lib.forms import BootstrapAttrsMixin
import contributors.models as cmodels


class UsernameForm(BootstrapAttrsMixin, forms.Form):
    username = forms.CharField(
            label=_("User name"), required=True,
            help_text=_("Enter the user name to which you are going to associate identifiers."
                        " It defaults to your user name."))

    def clean_username(self):
        data = self.cleaned_data["username"]
        if cmodels.User.objects.filter(username=data).exists():
            return data

        raise forms.ValidationError(
                _("Not a valid user name"), code="invalid")


class EmailIdentityForm(BootstrapAttrsMixin, forms.Form):
    email = forms.CharField(
            label=_("E-Mail"), required=True,
            help_text=_("Enter the email to associate to the user"))

    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.fields["email"].widget.attrs["placeholder"] = "user@example.org"

    def clean_email(self):
        data = self.cleaned_data["email"]
        if cmodels.Identifier.objects.filter(type="email", name=data).exists():
            return data

        raise forms.ValidationError(
                _("This email is not known to the site"), code="invalid")


class FingerprintIdentityForm(BootstrapAttrsMixin, forms.Form):
    fpr = forms.CharField(
            label=_("GPG key fingerprint"), required=True,
            help_text=_("Enter the fingerprint to associate to the user"))

    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.fields["fpr"].widget.attrs["placeholder"] = "1234 5678 9ABC DEF0 1234  5678 9ABC DEF0 1234 5678"

    def clean_fpr(self):
        data = self.cleaned_data["fpr"].replace(' ', '')
        if cmodels.Identifier.objects.filter(type="fpr", name=data).exists():
            return data

        raise forms.ValidationError(
                _("This fingerprint is not known to the site"), code="invalid")


class LoginIdentityForm(BootstrapAttrsMixin, forms.Form):
    login = forms.CharField(
            label=_("Login name"), required=True,
            help_text=_("Enter the LDAP username to associate to the user"))

    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.fields["login"].widget.attrs["placeholder"] = "username"

    def clean_login(self):
        data = self.cleaned_data["login"]
        if cmodels.Identifier.objects.filter(type="login", name=data).exists():
            return data

        raise forms.ValidationError(
                _("This login is not known to the site"), code="invalid")

claim/views.py
from __future__ import annotations
from django.core.exceptions import PermissionDenied
from django.core import mail, signing
from django import http
from django.conf import settings
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.contrib import messages
from dc.mixins import VisitorMixin
import contributors.models as cmodels
from .forms import UsernameForm, EmailIdentityForm, FingerprintIdentityForm, LoginIdentityForm


class Claim(VisitorMixin, FormView):
    template_name = "claim/claim.html"
    form_class = UsernameForm
    require_visitor = "user"

    def get(self, request, *args, **kw):
        if not self.request.user.is_dd:
            return redirect("claim:menu", self.request.user.username)
        else:
            return super().get(request, *args, **kw)

    def post(self, request, *args, **kw):
        dest = self.request.POST.get("action", "claim")
        if dest == "claim":
            if not self.request.user.is_dd:
                return redirect("claim:menu", self.request.user.username)
            else:
                return super().post(request, *args, **kw)
        else:
            if not self.request.user.is_dd:
                return redirect("claim:unclaim_menu", self.request.user.username)
            else:
                return super().post(request, *args, **kw)

    def get_initial(self):
        return {"username": self.request.user.username}

    def form_valid(self, form):
        dest = self.request.POST.get("action", "claim")
        if dest == "claim":
            return redirect("claim:menu", form.cleaned_data["username"])
        else:
            return redirect("claim:unclaim_menu", form.cleaned_data["username"])


class ClaimUserMixin:
    def load_objects(self):
        super().load_objects()
        self.target = get_object_or_404(cmodels.User, username=self.kwargs["username"])

    def check_permissions(self):
        super().check_permissions()
        if not self.request.user.is_dd and self.target != self.request.user:
            raise PermissionDenied()

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["target"] = self.target
        return ctx


class ClaimUser(ClaimUserMixin, VisitorMixin, TemplateView):
    template_name = "claim/menu.html"
    require_visitor = "user"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["login_form"] = LoginIdentityForm()
        ctx["fpr_form"] = FingerprintIdentityForm()
        ctx["email_form"] = EmailIdentityForm()
        return ctx


class ClaimEmail(ClaimUserMixin, VisitorMixin, FormView):
    template_name = "claim/claim_user_email.html"
    require_visitor = "user"
    form_class = EmailIdentityForm

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        email = self.request.POST.get("email")
        if self.request.user.is_dd and email is not None:
            if "@" not in email:
                email += "@"
            ctx["emails"] = cmodels.Identifier.objects.filter(type="email", name__istartswith=email).order_by("name")
        return ctx

    def form_valid(self, form):
        ident = get_object_or_404(cmodels.Identifier, type="email", name=form.cleaned_data["email"])

        if self.request.user.is_dd:
            # Do the association directly
            msg = f"Email {ident.name} associated to {self.target} from {ident.user} by {self.request.user}"
            ident.user = self.target
            ident.save()
            ident.add_log(msg)
        else:
            # Send email challenge
            token = signing.dumps({'u': self.request.user.pk, 'i': ident.pk})
            verify_url = reverse('claim:verify_email', args=[self.target.username])
            url = self.request.build_absolute_uri(f"{verify_url}?token={token}")
            message = f"""Hello,

{self.request.user} (who is probably you) wants to be credited on https://contributors.debian.org
for contributions made with this email address ({ident.name}).

If that is NOT correct, please ignore or delete this email.

If that is correct, please confirm by clicking this link, while you are logged in:
{url}

Thank you,

contributors.debian.org
"""
            mail_from = '{0} <{1}>'.format(settings.ADMINS[0][0], settings.ADMINS[0][1])
            mail.send_mail('Verify contributors.debian.org claim', message,
                           mail_from, [ident.name], fail_silently=False)
            msg = f"Challenge email sent to {ident.name}. Click on the verification link to complete the process."

        messages.info(self.request, msg)
        return redirect("claim:menu", self.target.username)


class ClaimLogin(ClaimUserMixin, VisitorMixin, FormView):
    template_name = "claim/claim_user_login.html"
    require_visitor = "dd"
    form_class = LoginIdentityForm

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        login = self.request.POST.get("login")
        if login is not None:
            ctx["logins"] = cmodels.Identifier.objects.filter(type="login", name__icontains=login).order_by("name")
        return ctx

    def form_valid(self, form):
        ident = get_object_or_404(cmodels.Identifier, type="login", name=form.cleaned_data["login"])
        msg = f"Login {ident.name} associated to {self.target} from {ident.user} by {self.request.user}"
        ident.user = self.target
        ident.save()
        ident.add_log(msg)
        messages.info(self.request, msg)
        return redirect("claim:menu", self.target.username)


class ClaimFingerprint(ClaimUserMixin, VisitorMixin, FormView):
    template_name = "claim/claim_user_fpr.html"
    require_visitor = "dd"
    form_class = FingerprintIdentityForm

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        fpr = self.request.POST.get("fpr")
        if fpr is not None:
            ctx["fprs"] = cmodels.Identifier.objects.filter(type="fpr", name__icontains=fpr).order_by("name")
        return ctx

    def form_valid(self, form):
        ident = get_object_or_404(cmodels.Identifier, type="fpr", name=form.cleaned_data["fpr"])
        msg = f"Fingreprint {ident.name} associated to {self.target} from {ident.user} by {self.request.user}"
        ident.user = self.target
        ident.save()
        ident.add_log(msg)
        messages.info(self.request, msg)
        return redirect("claim:menu", self.target.username)


class ClaimEmailVerify(ClaimUserMixin, VisitorMixin, TemplateView):
    template_name = "claim/validate_email.html"
    require_visitor = "user"

    def load_objects(self):
        super().load_objects()
        if self.request.method == "GET":
            self.token = self.request.GET.get("token")
        else:
            self.token = self.request.POST.get("token")
        if self.token is None:
            raise http.Http404

        try:
            self.decoded = signing.loads(self.token, max_age=3600 * 24 * 3)
        except (signing.BadSignature, signing.SignatureExpired):
            raise http.Http404

        self.ident = get_object_or_404(cmodels.Identifier, pk=self.decoded["i"])

    def check_permissions(self):
        super().check_permissions()
        user = get_object_or_404(cmodels.User, pk=self.decoded["u"])
        if user != self.target:
            raise PermissionDenied()

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["token"] = self.token
        ctx["ident"] = self.ident
        return ctx

    def post(self, request, *args, **kw):
        # Do the association
        msg = f"Email {self.ident.name} associated to {self.target} from {self.ident.user} by {self.request.user}"
        self.ident.user = self.target
        self.ident.save()
        self.ident.add_log(msg)
        messages.info(self.request, msg)
        return redirect("claim:menu", self.target.username)


class UnclaimMenu(ClaimUserMixin, VisitorMixin, TemplateView):
    template_name = "claim/unclaim_menu.html"
    require_visitor = "user"


class Unclaim(ClaimUserMixin, VisitorMixin, TemplateView):
    template_name = "claim/unclaim.html"
    require_visitor = "user"

    def load_objects(self):
        super().load_objects()
        self.ident = get_object_or_404(cmodels.Identifier, pk=self.kwargs["ident"])

    def check_permissions(self):
        super().check_permissions()
        if self.ident.user != self.target:
            raise PermissionDenied()

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["ident"] = self.ident
        return ctx

    def post(self, request, *args, **kw):
        msg = f"{self.ident.type} {self.ident.name} deassociated from {self.target} by {self.request.user}"
        self.ident.user = None
        self.ident.save()
        self.ident.add_log(msg)
        self.target.add_log(msg)
        messages.info(self.request, msg)
        return redirect("claim:unclaim_menu", self.target.username)

claim/templates/claim/base.html
{% extends "dc-base.html" %}

{% block content %}
<h1>Debian Contributors Page Template</h1>
{% endblock %}

claim/templates/claim/claim.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Claim identifiers</h1>

<p class="lead">
{% blocktrans %}
Associate identifiers to yourself or other people. As Debian Developer, you can
associate any identifier to any person: you can use this to help friends or
people in your teams get credited.
<b>Always ask</b> before associating an identifier to a person other than
you: do not associate people without their consent.
{% endblocktrans %}
</p>

<form method="POST" action="{{request.build_absolute_uri}}">{% csrf_token %}
  {% for f in form.hidden_fields %}{{f}}{% endfor %}
  {% for field in form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-10">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
  </div>
  {% endfor %}

<hr class="my-4">


<button type="submit" name="action" value="claim" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
<button type="submit" name="action" value="unclaim" class="btn btn-primary btn-lg"><span class="fa fa-unlink"></span> {% trans "Unclaim" %}</button>
</form>

</div>

{% endblock %}

claim/templates/claim/claim_user_email.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Claim email for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% if user.is_dd %}
{% blocktrans %}
Associate emails to the user you chose. As Debian Developer, you can
associate any email to any person: you can use this to help friends or
people in your teams get credited.
<b>Always ask</b> before associating an email to a person other than
you: do not associate people without their consent.
{% endblocktrans %}
{% else %}
Associate emails to your user: you will be sent a challenge email with a link
to click to prove that you control that address. If you need help, you can ask
a Debian Developer that knows you well to do the changes for you.
{% endif %}
</p>

<hr class="my-4">

<form method="POST" action="{% url 'claim:email' username=target.username %}">{% csrf_token %}
  {% for f in form.hidden_fields %}{{f}}{% endfor %}
  {% for field in form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-8">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
    <div class="col-sm-2">
      <button type="submit" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
    </div>
  </div>
  {% endfor %}
</form>

<a class="btn btn-secondary btn-lg" href="{% url 'claim:menu' username=target.username %}"><span class="fa fa-times"></span> {% trans "Cancel" %}</a>

</div>

{% if emails %}
<p class="lead">{% trans "Matching emails:" %}</p>

<ul>
  {% for email in emails %}
  <li>{{email.name}}{% if email.user_id %}
    {% if email.user_id == target.pk %}
    <b>{% blocktrans with target=target %} (already associated to {{target}}) {% endblocktrans %}</b>
    {% else %}
      {% trans " (associated)" %}
    {% endif %}
  {% endif %}</li>
  {% endfor %}
</ul>

{% endif %}

{% endblock %}

claim/templates/claim/claim_user_fpr.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Claim GPG key for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% blocktrans %}
Associate GPG keys to the user you chose. As Debian Developer, you can
associate any GPG key to any person: you can use this to help friends or
people in your teams get credited.
<b>Always ask</b> before associating an GPG key to a person other than
you: do not associate people without their consent.
{% endblocktrans %}
</p>

<hr class="my-4">

<form method="POST" action="{% url 'claim:fpr' username=target.username %}">{% csrf_token %}
  {% for f in form.hidden_fields %}{{f}}{% endfor %}
  {% for field in form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-8">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
    <div class="col-sm-2">
      <button type="submit" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
    </div>
  </div>
  {% endfor %}
</form>

<a class="btn btn-secondary btn-lg" href="{% url 'claim:menu' username=target.username %}"><span class="fa fa-times"></span> {% trans "Cancel" %}</a>

</div>

{% if fprs %}
<p class="lead">{% trans "Matching GPG fingerprints:" %}</p>

<ul>
  {% for fpr in fprs %}
  <li>{{fpr.name}}{% if fpr.user_id %}{% trans " (associated)" %}{% endif %}</li>
  {% endfor %}
</ul>

{% endif %}

{% endblock %}

claim/templates/claim/claim_user_login.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Claim login for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% blocktrans %}
Associate logins to the user you chose. As Debian Developer, you can
associate any login to any person: you can use this to help friends or
people in your teams get credited.
<b>Always ask</b> before associating a login to a person other than
you: do not associate people without their consent.
{% endblocktrans %}
</p>

<hr class="my-4">

<form method="POST" action="{% url 'claim:login' username=target.username %}">{% csrf_token %}
  {% for f in form.hidden_fields %}{{f}}{% endfor %}
  {% for field in form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-8">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
    <div class="col-sm-2">
      <button type="submit" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
    </div>
  </div>
  {% endfor %}
</form>

<a class="btn btn-secondary btn-lg" href="{% url 'claim:menu' username=target.username %}"><span class="fa fa-times"></span> {% trans "Cancel" %}</a>

</div>

{% if logins %}
<p class="lead">{% trans "Matching logins" %}</p>

<ul>
  {% for login in logins %}
  <li>{{login.name}}{% if login.user_id %}{% trans " (associated)" %}{% endif %}</li>
  {% endfor %}
</ul>

{% endif %}

{% endblock %}

claim/templates/claim/menu.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Claim identifiers for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% if user.is_dd %}
{% blocktrans %}
Associate identifiers to the user you chose. As Debian Developer, you can
associate any identifier to any person: you can use this to help friends or
people in your teams get credited.
<b>Always ask</b> before associating an identifier to a person other than
you: do not associate people without their consent.
{% endblocktrans %}
{% else %}
Associate identifiers to your user: you will be asked to prove that you control
the identifiers that you choose. If you need help, you can ask a Debian
Developer that knows you well to do the changes for you.
{% endif %}
</p>

<hr class="my-4">

<form method="POST" action="{% url 'claim:email' username=target.username %}">{% csrf_token %}
  {% for f in email_form.hidden_fields %}{{f}}{% endfor %}
  {% for field in email_form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-8">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
    <div class="col-sm-2">
    <button type="submit" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
    </div>
  </div>
  {% endfor %}
</form>

{% if user.is_dd %}
<form method="POST" action="{% url 'claim:fpr' username=target.username %}">{% csrf_token %}
  {% for f in fpr_form.hidden_fields %}{{f}}{% endfor %}
  {% for field in fpr_form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-8">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
    <div class="col-sm-2">
    <button type="submit" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
    </div>
  </div>
  {% endfor %}
</form>

<form method="POST" action="{% url 'claim:login' username=target.username %}">{% csrf_token %}
  {% for f in login_form.hidden_fields %}{{f}}{% endfor %}
  {% for field in login_form.visible_fields %}
  <div class="form-group row">
    <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
    <div class="col-sm-8">
      {{field}}
    <small class="text-muted">{{field.help_text}}</small>
    {% if field.errors %}
    <div class="text-danger">{{field.errors}}</div>
    {% endif %}
    </div>
    <div class="col-sm-2">
    <button type="submit" class="btn btn-primary btn-lg"><span class="fa fa-link"></span> {% trans "Claim" %}</button>
    </div>
  </div>
  {% endfor %}
</form>
{% endif %}

{% if messages %}
<hr class="my-4">

<ul class="list-group">
{% for message in messages %}
<li class="list-group-item
  {% if message.level_tag == 'error' %}list-group-item-danger{% endif %}
  {% if message.level_tag == 'warning' %}list-group-item-warning{% endif %}
  {% if message.level_tag == 'info' %}list-group-item-info{% endif %}
  "><span class="fa fa-{% if message.level_tag == 'info' %}info-circle{% else %}warning{% endif %}"></span> {{message}}</li>
{% endfor %}
</ul>
{% endif %}

</div>

{% endblock %}

claim/templates/claim/unclaim.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Unclaim identifiers for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% blocktrans with type=ident.type name=ident.name target=target %}
Deassociate {{type}} {{name}} from user {{target}}?
{% endblocktrans %}
</p>

<form action="{{request.build_absolute_uri}}" method="POST">{% csrf_token %}
  <button type="submit" class="btn btn-lg btn-primary"><span class="fa fa-unlink"></span> {% trans "Deassociate" %}</button>
  <a class="btn btn-lg btn-secondary" href="{% url 'claim:unclaim_menu' username=target.username %}"><span class="fa fa-times"></span> {% trans "Cancel" %}</a>
</form>

</div>

{% endblock %}

claim/templates/claim/unclaim_menu.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Unclaim identifiers for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% if user.is_dd %}
{% blocktrans %}
Deassociate identifiers to the user you chose. As Debian Developer, you can
deassociate any identifier from any person: you can use this to help friends or
people in your teams fix issues with their contributor mappings.
<b>Always ask</b> before deassociating an identifier from a person other than
you: do not change people's information without their consent.
{% endblocktrans %}
{% else %}
Deassociate identifiers from your user. If you need help, you can ask a Debian
Developer that knows you well to do the changes for you.
{% endif %}
</p>

{% if messages %}
<hr class="my-4">

<ul class="list-group">
{% for message in messages %}
<li class="list-group-item
  {% if message.level_tag == 'error' %}list-group-item-danger{% endif %}
  {% if message.level_tag == 'warning' %}list-group-item-warning{% endif %}
  {% if message.level_tag == 'info' %}list-group-item-info{% endif %}
  "><span class="fa fa-{% if message.level_tag == 'info' %}info-circle{% else %}warning{% endif %}"></span> {{message}}</li>
{% endfor %}
</ul>
{% endif %}

<hr class="my-4">

<div class="list-group">
{% for ident in target.identifiers.all %}
<a class="list-group-item list-group-item-action" href="{% url 'claim:unclaim' username=target.username ident=ident.pk %}">
  {% if ident.type == "email" %}
  <span class="fa fa-at"></span> Email: {{ident.name}}
  {% elif ident.type == "fpr" %}
  <span class="fa fa-gnupg"></span> GPG key: {{ident.name}}
  {% elif ident.type == "login" %}
  <span class="fa fa-user"></span> Login: {{ident.name}}
  {% else %}
  <span class="fa fa-chevron-circle-right"></span> {{ident.type}}: {{ident.name}}
  {% endif %}
</a>
{% empty %}
<span class="list-group-items">{% trans 'There are no identifiers associated at the moment' %}</span>
{% endfor %}
</div>

</div>

{% endblock %}

claim/templates/claim/validate_email.html
{% extends "claim/base.html" %}
{% load i18n %}

{% block content %}

<div class="jumbotron">
  <h1>Associate identifiers for <a href="{{target.get_absolute_url}}">{{target}}</a></h1>

<p class="lead">
{% blocktrans with type=ident.type name=ident.name target=target %}
Associate {{type}} {{name}} to user {{target}}?
{% endblocktrans %}
</p>

<form action="{{request.build_absolute_uri}}" method="POST">{% csrf_token %}
  <input type="hidden" name="token" value="{{token}}"></input>
  <button type="submit" class="btn btn-lg btn-primary"><span class="fa fa-link"></span> {% trans "Associate" %}</button>
  <a class="btn btn-lg btn-secondary" href="{% url 'contributors' %}"><span class="fa fa-times"></span> {% trans "Cancel" %}</a>
</form>

</div>

{% endblock %}