dc/urls.py
from __future__ import annotations
from django.urls import include, path
from django.views.generic import TemplateView
import django.conf.urls
from contributors import views as cviews
import dclayout.views as dcviews
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'contributors', cviews.ContributorViewSet, "contributors")
router.register(r'identifiers', cviews.IdentifierViewSet, "identifiers")

django.conf.urls.handler403 = dcviews.Error403.as_view()
django.conf.urls.handler404 = dcviews.Error404.as_view()
django.conf.urls.handler500 = dcviews.Error500.as_view()


urlpatterns = [
    path('', cviews.Contributors.as_view(), name="contributors"),
    path('license/', TemplateView.as_view(template_name='license.html'), name="root_license"),
    path('about/privacy/', TemplateView.as_view(template_name='privacy.html'), name="root_privacy"),
    path('admin/', admin.site.urls),
    path('contributors/', include('contributors.urls')),
    path('contributor/', include('contributor.urls')),
    path('source/', include("sources.urls")),
    path('mia/', include("mia.urls")),
    path('importer/', include("importer.urls")),
    path('claim/', include("claim.urls")),
    path('api/', include(router.urls)),
    path('deploy/', include("deploy.urls")),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),
]

sources/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "sources"

urlpatterns = [
    path('', views.SourcesList.as_view(), name="list"),
    path('add/', views.SourceCreate.as_view(), name='add'),
    path('<sname>/', views.SourceView.as_view(), name='view'),
    path('<sname>/ctype/<name>/', views.CtypeView.as_view(), name='ctype_view'),
    path('<sname>/update/', views.SourceUpdate.as_view(), name='update'),
    path('<sname>/delete/', views.SourceDelete.as_view(), name='delete'),
    path('<sname>/delete/contributions/', views.SourceDeleteContributions.as_view(), name='delete_contributions'),
    path('<sname>/backups/', views.SourceBackupList.as_view(), name='backup_list'),
    path('<sname>/backups/<int:backup_id>/', views.SourceBackupDownload.as_view(), name='backup_download'),
    path('<sname>/members/', views.SourceMembers.as_view(), name='members'),
    path('<sname>/members/add/', views.SourceMembersAdd.as_view(), name='members_add'),
    path('<sname>/members/delete/', views.SourceMembersDelete.as_view(), name='members_delete'),
    path('<sname>/ctypes/add/', views.ContributionTypeCreate.as_view(), name='ctype_add'),
    path('<sname>/ctype/<name>/update/', views.ContributionTypeUpdate.as_view(), name='ctype_update'),
    path('<sname>/ctype/<name>/delete/', views.ContributionTypeDelete.as_view(), name='ctype_delete'),
    path('<sname>/ctype/<name>/delete/contributions/', views.ContributionTypeDeleteContributions.as_view(),
         name='ctype_delete_contributions'),
    path('<sname>/user-settings/', views.SourceUserSettings.as_view(), name='user_settings'),
]

sources/models.py
from django.db import models

# Cf. contributors/models.py

# Create your models here.

sources/views.py
from django import http
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import DetailView, TemplateView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.core.exceptions import PermissionDenied
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper
from django.forms import ModelForm
from dc.mixins import VisitorMixin
from dc.lib.forms import BootstrapAttrsMixin
import contributors.models as cmodels
import logging
import os

log = logging.getLogger(__name__)


class SourcesList(VisitorMixin, TemplateView):
    template_name = "sources/list.html"

    def get_context_data(self, **kw):
        ctx = super(SourcesList, self).get_context_data(**kw)

        sources = []
        have_user = self.request.user.is_authenticated
        for s in cmodels.Source.objects.all().order_by("name"):
            if have_user:
                s.perm_can_admin = s.can_admin(self.request.user)
                s.perm_can_add_self = s.can_add_member(self.request.user, self.request.user)
            else:
                s.perm_can_admin = False
                s.perm_can_add_self = False
            sources.append(s)

        ctx["sources"] = sources

        return ctx


class SourceForm(BootstrapAttrsMixin, ModelForm):
    class Meta:
        model = cmodels.Source
        exclude = ("last_import", "last_contribution", "admins",)


class VisitSourceMixin(VisitorMixin):
    def load_objects(self):
        super(VisitSourceMixin, self).load_objects()
        self.source = get_object_or_404(cmodels.Source, name=self.kwargs["sname"])
        self.perm_source_admin = self.source.can_admin(self.request.user)
        self.perm_source_add_member = self.source.can_add_member(self.request.user, self.request.user)

    def check_visitor_permission(self, perm):
        if perm == "source_admin":
            return self.perm_source_admin
        elif perm == "source_add_member":
            return self.perm_source_add_member
        else:
            return super().check_visitor_permission(perm)

    def get_context_data(self, **kw):
        ctx = super(VisitSourceMixin, self).get_context_data(**kw)
        ctx["source"] = self.source
        ctx["perm_source_admin"] = self.perm_source_admin
        ctx["perm_source_add_member"] = self.perm_source_add_member
        return ctx


class SourceView(VisitSourceMixin, TemplateView):
    template_name = "sources/view.html"

    def get_context_data(self, **kw):
        from django.db.models import Min, Max
        ctx = super(SourceView, self).get_context_data(**kw)
        ctypes = self.source.contribution_types.all().order_by("desc")
        ctx["ctypes"] = ctypes

        # Reaggregate AggregatedPersonContribution by user
        ctx["contribs"] = (cmodels.AggregatedPersonContribution.objects
                           .filter(ctype__source=self.source)
                           .values("user", "user__full_name", "user__username")
                           .annotate(begin=Min("begin"), until=Max("until"))
                           .order_by("-until", "user__username"))
        for c in ctx["contribs"]:
            c["user_url"] = reverse(
                    "contributor:detail",
                    args=[c["user__username"]])
        # Unassociated identifiers
        is_source_admin = self.source.can_admin(self.request.user)
        if is_source_admin is True:
            ctx["can_admin"] = True
            ctx["unassociated"] = (cmodels.Contribution.objects.filter(identifier__user=None, type__in=ctypes)
                                   .values("identifier__name", "begin", "until", "type__name")
                                   .order_by("-until")[:100]) # Limit to 100 until we have some pagination
        return ctx


class SourceMembers(VisitSourceMixin, TemplateView):
    template_name = "sources/members.html"
    require_visitor = "source_add_member"

    def get_context_data(self, **kw):
        ctx = super(SourceMembers, self).get_context_data(**kw)
        ctx["can_admin"] = self.source.can_admin(self.request.user)
        return ctx


class SourceMembersAdd(VisitSourceMixin, View):
    require_visitor = "source_add_member"

    def post(self, request, *args, **kw):
        user = get_object_or_404(cmodels.User, username=request.POST.get("name", None))
        if not self.source.can_add_member(request.user, user):
            raise PermissionDenied
        self.source.admins.add(user)
        return redirect("sources:members", sname=self.source.name)


class SourceMembersDelete(VisitSourceMixin, View):
    require_visitor = "source_admin"

    def post(self, request, *args, **kw):
        user = get_object_or_404(cmodels.User, username=request.POST.get("name", None))
        self.source.admins.remove(user)
        return redirect("sources:members", sname=self.source.name)


class CtypeView(VisitSourceMixin, TemplateView):
    template_name = "sources/cview.html"

    def get_context_data(self, **kw):
        ctx = super(CtypeView, self).get_context_data(**kw)
        ct = get_object_or_404(cmodels.ContributionType, source=self.source, name=self.kwargs["name"])
        ctx["ct"] = ct
        ctx["contribs"] = cmodels.AggregatedPersonContribution.objects.filter(ctype=ct).select_related("user") \
                                 .order_by("-until", "user__username")
        return ctx


class SourceCreate(VisitorMixin, CreateView):
    template_name = "sources/source_form.html"
    model = cmodels.Source
    form_class = SourceForm
    success_url = reverse_lazy('sources:list')

    def dispatch(self, request, *args, **kw):
        if not request.user.is_authenticated:
            raise PermissionDenied
        if not request.user.is_dd:
            raise PermissionDenied
        return super(SourceCreate, self).dispatch(request, *args, **kw)

    def form_valid(self, *args, **kw):
        res = super(SourceCreate, self).form_valid(*args, **kw)
        user = get_object_or_404(cmodels.User, pk=self.request.user.pk)
        self.object.admins.add(user)
        return res


class SourceMixin(VisitSourceMixin):
    model = cmodels.Source
    slug_field = "name"
    slug_url_kwarg = "sname"
    form_class = SourceForm
    success_url = reverse_lazy('sources:list')
    require_visitor = "source_admin"

    def get_object(self, queryset=None):
        return self.source


class SourceUpdate(SourceMixin, UpdateView):
    template_name = "sources/source_form.html"


class SourceDelete(SourceMixin, DeleteView):
    template_name = "sources/source_confirm_delete.html"


class SourceBackupList(SourceMixin, DetailView):
    template_name = "sources/source_backup_list.html"

    def get_context_data(self, **kwargs):
        ctx = super(SourceBackupList, self).get_context_data(**kwargs)
        ctx["backups"] = list(self.object.backups())[::-1]
        return ctx


class SourceBackupDownload(SourceMixin, DetailView):
    def get(self, request, *args, **kwargs):
        source = self.get_object()
        backup_id = kwargs["backup_id"]
        backup_dir = source.get_backup_dir()
        if not backup_dir:
            raise http.Http404
        backup_file = os.path.join(backup_dir, backup_id + ".json.gz")
        if not os.path.exists(backup_file):
            raise http.Http404

        response = StreamingHttpResponse(FileWrapper(open(backup_file, "rb")),
                                         content_type="application/json")
        response["Content-Length"] = os.path.getsize(backup_file)
        response["Content-Encoding"] = "gzip"
        response["Content-Disposition"] = "attachment; filename={}-{}.json".format(
            backup_id, source.name)
        return response


class ContributionTypeForm(BootstrapAttrsMixin, ModelForm):
    class Meta:
        model = cmodels.ContributionType
        exclude = ('source',)


class ContributionTypeMixin(SourceMixin):
    model = cmodels.ContributionType
    slug_field = "name"
    slug_url_kwarg = "name"
    form_class = ContributionTypeForm
    require_visitor = "source_admin"

    def load_objects(self):
        super(ContributionTypeMixin, self).load_objects()
        self.ctype = get_object_or_404(cmodels.ContributionType, source=self.source, name=self.kwargs["name"])

    def get_object(self):
        return self.ctype

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(source=self.source)
        return qs

    def get_success_url(self):
        return reverse('sources:update', kwargs={"sname": self.source.name})


class ContributionTypeCreate(SourceMixin, CreateView):
    template_name = "sources/contributiontype_form.html"
    model = cmodels.ContributionType
    form_class = ContributionTypeForm

    def get_success_url(self):
        return reverse('sources:update', kwargs={"sname": self.source.name})

    def form_valid(self, form):
        form.instance.source = self.source
        return super(ContributionTypeCreate, self).form_valid(form)


class ContributionTypeUpdate(ContributionTypeMixin, UpdateView):
    template_name = "sources/contributiontype_form.html"


class ContributionTypeDelete(ContributionTypeMixin, DeleteView):
    template_name = "sources/contributiontype_confirm_delete.html"


class SourceDeleteContributions(SourceMixin, TemplateView):
    template_name = "sources/source_contributions_confirm_delete.html"
    require_visitor = "source_admin"

    def post(self, request, *args, **kwargs):
        # This implementation is "minimalist", not generic neither reusable.
        # Assume to inherit from SourceMixin or ContributionTypeMixin,
        # elsewise all is broken.

        for ct in self.source.contribution_types.all():
            ct.contributions.all().delete()
            cmodels.AggregatedPersonContribution.recompute(ctype=ct)
        cmodels.AggregatedSource.recompute(source=self.source)

sources/templates/sources/base.html
{% extends "dc-base.html" %}

{% block nav_left_items %}{# Top links #}
{{block.super}}
{% if source %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="fa fa-address-book-o"></span>
    {{source}}
  </a>
  <div class="dropdown-menu dropdown-menu" role="menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{{source.get_absolute_url}}"><span class="fa fa-address-book-o"></span> View</a>

    {% if not user.is_anonymous %}
    <a class="dropdown-item" href="{% url 'sources:user_settings' sname=source.name %}"><span class="fa fa-gear"></span> User settings</a>
    {% endif %}

    {% if perm_source_admin %}
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'sources:update' sname=source.name %}"><span class="fa fa-gears"></span> Configure</a>
    <a class="dropdown-item" href="{% url 'importer_source_status' sname=source.name %}"><span class="fa fa-history"></span> Import logs</a>
    <a class="dropdown-item" href="{% url 'sources:backup_list' sname=source.name %}"><span class="fa fa-cloud-download"></span> Backups</a>
    {% endif %}
  </div>
</li>
{% endif %}
{% endblock %}

{% block content %}
<h1>Debian Contributors Page Template</h1>
{% endblock %}

sources/templates/sources/contributiontype_confirm_delete.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Delete contribution type {{object}}?</h1>

<form action="." method="POST">{% csrf_token %}
  <button class="btn btn-warning" type="submit">{% trans "Delete" %}</button>
</form>

<a class="btn btn-primary" href="{% url 'sources:update' sname=object.source.name %}">{% trans "Do not delete" %}</a>

{% endblock %}

sources/templates/sources/contributiontype_contributions_confirm_delete.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Delete contributions for contribution type {{object}}?</h1>

<form action="." method="POST">{% csrf_token %}
  <button class="btn btn-warning" type="submit">{% trans "Delete" %}</button>
</form>

<a class="btn btn-primary" href="{% url 'sources:update' sname=object.source.name %}">{% trans "Do not delete" %}</a>

{% endblock %}

sources/templates/sources/contributiontype_form.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

{% if object %}
<h1>Edit {{object}} contribution type</h2>
{% else %}
<h1>Create new Debian Contributors contribution type</h2>
{% endif %}

<form action="." method="POST">{% csrf_token %}
  {{ form.non_field_errors }}

  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}

  {% for field in form %}
  <div class="form-group">
  {{field.label_tag}}
  {% if field.errors %}
  Issues with the field:
  {{field.errors}}
  {% endif %}
  {{field}}
  <small class="form-text text-muted">{{field.help_text}}</small>
  </div>
  {% endfor %}

  <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
</form>

{% endblock %}

sources/templates/sources/cview.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Debian Contributors {{source.name}} {{ct.desc}} data source</h2>

<h2>Contributions</h2>

<p class="lead">{{contribs.count}} contributors/contributions tracked:</p>

<table id="contribs" class="table table-sm tablesorter">
<thead>
    <tr>
        <th>Name</th>
        <th>Since</th>
        <th>Until</th>
    </tr>
</thead>
<tbody>
    {% for c in contribs %}
    <tr>
      <td><a href="{{c.user.get_absolute_url}}">{{c.user.full_name|default:c.user.username}}</a></td>
      <td data-sort="{{c.begin|date:"Ymd"}}">{{c.begin}}</td>
      <td data-sort="{{c.until|date:"Ymd"}}">{{c.until}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

sources/templates/sources/list.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Debian Contributors data sources</h1>

<p class="lead">
This is a list of all the data sources that feed the Debian Contributors list.
To create a new one, see
<a href="https://wiki.debian.org/DebianContributors">the wiki</a> and
<a href="https://salsa.debian.org/python-team/modules/python-debiancontributors/blob/master/README.md">python-debiancontributors</a>.
</p>

<table id="sources" class="table table-sm tablesorter {{class}}">
<thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Last submission</th>
        <th>Latest contribution</th>
        <th>Admins</th>
        {% if user.is_authenticated %}
        <th>Actions</th>
        {% endif %}
    </tr>
</thead>
<tbody>
    {% for s in sources %}
    <tr>
      <td><a href="{{s.get_absolute_url}}">{{s.name}}</a></td>
      <td>{{s.desc}}</td>
      <td data-sort="{{s.last_import|date:"Ymd"}}">
        {% if s.last_import %}
          {{s.last_import|timesince}} ago
        {% else %}
          none
        {% endif %}
      </td>
      <td data-sort="{{s.last_contribution|date:"Ymd"}}">
        {% if s.last_contribution %}
          {{s.last_contribution|timesince}} ago
        {% else %}
          none
        {% endif %}
      </td>
      <td>
        {% for u in s.admins.all %}
        <a href="{{u.get_absolute_url}}">{{u.username}}</a>
        {% endfor %}
      </td>
      {% if user.is_authenticated %}
      <td>
        <a class="btn btn-sm btn-primary" href="{% url 'importer_source_status' sname=s.name %}">Imports</a>
        {% if s.perm_can_admin %}
        <a class="btn btn-sm btn-primary" href="{% url 'sources:update' sname=s.name %}">Edit</a>
        {% endif %}
        {% if s.perm_can_admin or s.perm_can_add_self %}
        <a class="btn btn-sm btn-primary" href="{% url 'sources:members' sname=s.name %}">Members</a>
        {% endif %}
        {% if s.perm_can_admin %}
        <a class="btn btn-sm btn-warning" href="{% url 'sources:delete' sname=s.name %}">Delete</a>
        {% endif %}
        {% if s.perm_can_admin %}
        <a class="btn btn-sm btn-warning" href="{% url 'sources:delete_contributions' sname=s.name %}">Delete all contributions</a>
        {% endif %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
</tbody>
{% if user.is_authenticated %}
<tfoot>
  <tr>
    <td colspan="6">
      <a href="{% url 'sources:add' %}">Create a new data source</a>
    </td>
  </tr>
</tfoot>
{% endif %}
</table>

<p>
<a href="{% url 'contributors_export_sources' %}">Export all sources to JSON</a>
</p>

{% endblock %}

sources/templates/sources/members.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block relatedpages %}
{% if not user.is_anonymous %}
<a href="{% url 'sources:update' sname=source.name %}">configure</a>
{% endif %}
{{block.super}}
{% endblock %}

{% block content %}

<h1>Configure admins for {{source.name}} data source</h2>

<h2>Admin list</h2>

<table class="table" id="admins">
<thead>
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>
</thead>
<tbody>
    {% for u in source.admins.all %}
    <tr>
      <td><a href="{{u.get_absolute_url}}">{{u}}</a></td>
      <td>
        {% if can_admin %}
        <form action="{% url 'sources:members_delete' sname=source.name %}" method="POST">{% csrf_token %}
          <input type="hidden" name="name" value="{{u.username}}">
          <button class="btn btn-warning" type="submit">{% trans "Delete" %}</button>
        </form>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
  <tr>
    <td colspan="2">
      <form action="{% url 'sources:members_add' sname=source.name %}" method="POST">{% csrf_token %}
        {% if can_admin %}
        <div class="form-group">
        <label for="add_username">{% trans "Add admin user" %}</label>
        <input class="form-control" type="text" name="name" id="add_username" placeholder="Username">
        </div>
        <button class="btn btn-primary" type="submit">{% trans "Add" %}</button>
        {% else %}
        <input type="hidden" name="name" value="{{request.user.username}}">
        <button class="btn btn-primary" type="submit">{% trans "Add me as an admin" %}</button>
        {% endif %}
      </form>
    </td>
  </tr>
</tfood>
</table>

{% endblock %}

sources/templates/sources/source_backup_list.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Backups for '{{object.name}}'</h1>

<table id="sources" class="table table-sm tablesorter">
<thead>
    <tr>
        <th>Backup time</th>
        <th>Identifiers</th>
        <th>Contributions</th>
        <th>Contribution types</th>
        <th>Actions</th>
    </tr>
</thead>
<tbody>
  {% for b in backups %}
  <tr>
    <td>{{b.backup_time}}</td>
    <td>{{b.ident_count}}</td>
    <td>{{b.contrib_count}}</td>
    <td>
      {% for ct in b.contrib_types %}
      <a href="{% url 'sources:ctype_view' sname=object.name name=ct %}">{{ct}}</a>
      {% endfor %}
    </td>
    <td>
      <a href="{% url 'sources:backup_download' sname=object.name backup_id=b.id %}">Download</a>
    </td>
  </tr>
  {% endfor %}
</tbody>
</table>


{% endblock %}

sources/templates/sources/source_confirm_delete.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Delete source {{object}}?</h1>

<form action="." method="POST">{% csrf_token %}
  <button class="btn btn-warning" type="submit">{% trans "Delete" %}</button>
</form>

<a class="btn btn-primary" href="{% url 'sources:list' %}">{% trans "Do not delete" %}</a>

{% endblock %}

sources/templates/sources/source_contributions_confirm_delete.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Delete contributions for source {{source}}?</h1>

<form action="." method="POST">{% csrf_token %}
  <button class="btn btn-warning" type="submit">{% trans "Delete" %}</button>
</form>

<a class="btn btn-primary" href="{% url 'sources:list' %}">{% trans "Do not delete" %}</a>

{% endblock %}

sources/templates/sources/source_form.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

{% if object %}
<h1>Edit {{object}} data source</h2>

<div class="card">
  <div class="card-header">Example post command</div>
  <div class="card-body">
    <pre class="mb-0">
curl https://{{ request.META.HTTP_HOST }}{% url 'contributors_post' %} \
     -F source="{{object.name}}" -F auth_token="{{object.auth_token}}" \
     -F data_compression=gzip -F data=@filename.json.gz</pre>
    <small>Also supported: <tt>-F data=@filename.json</tt> and
      <tt>-F data_compression=xz -F data=@filename.json.xz</tt>.</small>
  </div>
</div>
{% else %}
<h1>Create new Debian Contributors data source</h2>
{% endif %}

<form action="." method="POST">{% csrf_token %}
  {{ form.non_field_errors }}

  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}

  {% for field in form %}
  <div class="form-group">
    {{field.label_tag}}
    {% if field.errors %}
    Issues with the field:
    {{field.errors}}
    {% endif %}
    {{field}}
    <small class="form-text text-muted">
    {{field.help_text}}
    </small>
  </div>
  {% endfor %}

  <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
</form>

{% if object %}
<h2 class="mt-3">Contribution types</h2>

<table id="ctypes" class="table table-sm tablesorter {{class}}">
<thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Contributor description</th>
        <th>Actions</th>
    </tr>
</thead>
<tbody>
    {% for c in object.contribution_types.all %}
    <tr>
        <td><a href="{{c.get_absolute_url}}">{{c.name}}</a></td>
        <td>{{c.desc}}</td>
        <td>{{c.contrib_desc}}</td>
        <td>
          <a class="btn btn-sm btn-primary" href="{% url 'sources:ctype_update' sname=object.name name=c.name %}">Edit</a>
          <a class="btn btn-sm btn-warning" href="{% url 'sources:ctype_delete' sname=object.name name=c.name %}">Delete</a>
          <a class="btn btn-sm btn-warning" href="{% url 'sources:ctype_delete_contributions' sname=object.name name=c.name %}">Delete all contributions</a>
        </td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
  <tr>
    <td colspan="4">
      <a href="{% url 'sources:ctype_add' sname=object.name %}">Create new contribution type</a>
    </td>
  </tr>
</tfoot>
</table>


{% endif %}

{% endblock %}

sources/templates/sources/source_user_settings.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<div class="container-fluid">

<h1>User settings for '{{source.name}}'</h1>

<p class="lead">
From here you can control if you are hidden in {{source.name}}.
</p>

<form method="POST" action="{% url 'sources:user_settings' sname=source.name %}">{% csrf_token %}

<div class="form-group form-check">
<input type="checkbox" class="form-check-input" name="hide" {% if settings and settings.hidden %}checked="checked"{% endif %}>
<label class="form-check-label" for="hide">Hide your contributions in {{source.name}}</label>
</div>

<button class="btn btn-primary">{% trans "Submit" %}</button>

</form>

</div>

{% endblock %}

sources/templates/sources/view.html
{% extends "sources/base.html" %}
{% load i18n %}

{% block content %}

<h1>Debian Contributors '{{source.name}}' data source</h1>

<p class="lead">
  <i>{{source.desc}}</i>

  {% if source.url %}
  (<a href="{{source.url}}">more info</a>)
  {% endif %}
</p>

<h2>Contribution types</h2>

<table id="ctypes" class="table table-sm tablesorter">
<thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
</thead>
<tbody>
    {% for c in ctypes %}
    <tr>
      <td><a href="{{c.get_absolute_url}}">{{c.name}}</a></td>
      <td>{{c.desc}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>

<h2>Contributors</h2>
<p>{{contribs.count}} known contributors:</p>

<table id="contribs" class="table table-sm tablesorter">
<thead>
    <tr>
        <th>Name</th>
        <th>Since</th>
        <th>Until</th>
    </tr>
</thead>
<tbody>
    {% for c in contribs %}
    <tr>
      <td><a href="{{c.user_url}}">{{c.user__full_name|default:c.user__username}}</a></td>
      <td data-sort="{{c.begin|date:"Ymd"}}">{{c.begin}}</td>
      <td data-sort="{{c.until|date:"Ymd"}}">{{c.until}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% if can_admin %}
<h2>Unmapped contributors</h2>

<p>Last {{unassociated.count}} contributors which we could not map to a Debian or Alioth account:</p>

<table id="contribs" class="table table-sm tablesorter">
<thead>
  <tr>
    <th>Name</th>
    <th>Since</th>
    <th>Until</th>
    <th>Type</th>
  </tr>
</thead>
<tbody>
    {% for u in unassociated %}
    <tr>
      <td>{{u.identifier__name}}</a></td>
      <td data-sort="{{u.begin|date:"Ymd"}}">{{u.begin}}</td>
      <td data-sort="{{u.until|date:"Ymd"}}">{{u.until}}</td>
      <td data-sort="{{u.type__name}}">{{u.type__name}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% endif %}

{% endblock %}