claim/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "claim"

urlpatterns = [
    path('', views.Claim.as_view(), name="claim"),
    path('<username>/', views.ClaimUser.as_view(), name="menu"),
    path('<username>/email/', views.ClaimEmail.as_view(), name="email"),
    path('<username>/login/', views.ClaimLogin.as_view(), name="login"),
    path('<username>/fpr/', views.ClaimFingerprint.as_view(), name="fpr"),
    path('<username>/email/verify', views.ClaimEmailVerify.as_view(), name="verify_email"),
    path('<username>/unclaim/', views.UnclaimMenu.as_view(), name="unclaim_menu"),
    path('<username>/unclaim/<int:ident>/', views.Unclaim.as_view(), name="unclaim"),
    # path('<name>/unclaim/', views.Unclaim.as_view(), name="unclaim"),
]

dc/urls.py
from __future__ import annotations
from django.urls import include, path
from django.views.generic import TemplateView
import django.conf.urls
from contributors import views as cviews
import dclayout.views as dcviews
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'contributors', cviews.ContributorViewSet, "contributors")
router.register(r'identifiers', cviews.IdentifierViewSet, "identifiers")

django.conf.urls.handler403 = dcviews.Error403.as_view()
django.conf.urls.handler404 = dcviews.Error404.as_view()
django.conf.urls.handler500 = dcviews.Error500.as_view()


urlpatterns = [
    path('', cviews.Contributors.as_view(), name="contributors"),
    path('license/', TemplateView.as_view(template_name='license.html'), name="root_license"),
    path('about/privacy/', TemplateView.as_view(template_name='privacy.html'), name="root_privacy"),
    path('admin/', admin.site.urls),
    path('contributors/', include('contributors.urls')),
    path('contributor/', include('contributor.urls')),
    path('source/', include("sources.urls")),
    path('mia/', include("mia.urls")),
    path('importer/', include("importer.urls")),
    path('claim/', include("claim.urls")),
    path('api/', include(router.urls)),
    path('deploy/', include("deploy.urls")),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),
]

impersonate/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "impersonate"

urlpatterns = [
    # Impersonate a user
    path('impersonate/', views.Impersonate.as_view(), name="impersonate"),
    path('whoami/', views.Whoami.as_view(), name="whoami"),
]

signon/urls.py
from django.urls import path
from . import views

app_name = "signon"

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('logout/<name>/', views.Logout.as_view(), name='logout_identity'),
    path('oidc/callback/<name>/', views.OIDCAuthenticationCallbackView.as_view(), name='oidc_callback'),
    path('whoami/', views.Whoami.as_view(), name='whoami'),
    path('link/<provider>/<int:pk>/', views.Link.as_view(), name='link'),
    path('unlink/<provider>/', views.Unlink.as_view(), name='unlink'),
]

sources/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "sources"

urlpatterns = [
    path('', views.SourcesList.as_view(), name="list"),
    path('add/', views.SourceCreate.as_view(), name='add'),
    path('<sname>/', views.SourceView.as_view(), name='view'),
    path('<sname>/ctype/<name>/', views.CtypeView.as_view(), name='ctype_view'),
    path('<sname>/update/', views.SourceUpdate.as_view(), name='update'),
    path('<sname>/delete/', views.SourceDelete.as_view(), name='delete'),
    path('<sname>/delete/contributions/', views.SourceDeleteContributions.as_view(), name='delete_contributions'),
    path('<sname>/backups/', views.SourceBackupList.as_view(), name='backup_list'),
    path('<sname>/backups/<int:backup_id>/', views.SourceBackupDownload.as_view(), name='backup_download'),
    path('<sname>/members/', views.SourceMembers.as_view(), name='members'),
    path('<sname>/members/add/', views.SourceMembersAdd.as_view(), name='members_add'),
    path('<sname>/members/delete/', views.SourceMembersDelete.as_view(), name='members_delete'),
    path('<sname>/ctypes/add/', views.ContributionTypeCreate.as_view(), name='ctype_add'),
    path('<sname>/ctype/<name>/update/', views.ContributionTypeUpdate.as_view(), name='ctype_update'),
    path('<sname>/ctype/<name>/delete/', views.ContributionTypeDelete.as_view(), name='ctype_delete'),
    path('<sname>/ctype/<name>/delete/contributions/', views.ContributionTypeDeleteContributions.as_view(),
         name='ctype_delete_contributions'),
    path('<sname>/user-settings/', views.SourceUserSettings.as_view(), name='user_settings'),
]

dclayout/models.py
from django.db import models

# Create your models here.

dclayout/views.py
from __future__ import annotations
import urllib.parse
from django.views.generic import TemplateView
from dclayout.mixins import DCLayoutMixin
from signon.views import LoginMixin
import logging

log = logging.getLogger(__name__)


class Error403(DCLayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 403
            return res
        except Exception as e:
            log.error("403 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "403.html")]


class Error404(DCLayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 404
            return res
        except Exception as e:
            log.error("404 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "404.html")]

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)

        exception_repr = self.kwargs["exception"].__class__.__name__
        # Try to get an "interesting" exception message, if any (and not the ugly
        # Resolver404 dictionary)
        try:
            message = self.kwargs["exception"].args[0]
        except (AttributeError, IndexError):
            pass
        else:
            if isinstance(message, str):
                exception_repr = message
        ctx['request_path'] = urllib.parse.quote(self.request.path)
        ctx['exception'] = exception_repr
        return ctx


class Error500(DCLayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 500
            return res
        except Exception as e:
            log.error("500 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "500.html")]

dclayout/templates/dc-base.html
{% extends "debian-bootstrap4-base.html" %}
{% load i18n %}

{% block navbar_brand_url %}{% url 'contributors' %}{% endblock %}

{% block title %}{% trans "Debian Contributors" %}{% endblock %}

{% block head %}
{{block.super}}
<link rev="made" href="mailto:nm@debian.org">
<link type="text/css" rel="stylesheet" media="all" href="{{STATIC_URL}}css/dc.css">
<script src="{{STATIC_URL}}js/dc.js"></script>
{% endblock %}

{% block nav_searchbox %}{% comment %}No search feature in Contributors site yet{% endcomment %}{% endblock %}

{% block nav_left_items %}{# Top links #}
  <li class="nav-item"><a class="nav-link" href="{% url 'contributors' %}"><span class="fa fa-users"></span> {% trans "Contributors" %}</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'sources:list' %}"><span class="fa fa-address-book"></span> {% trans "Data sources" %}</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'site_status' %}"><span class="fa fa-tachometer"></span> {% trans "Site status" %}</a></li>  
  <li class="nav-item"><a class="nav-link" href="https://nm.debian.org/members"><span class="fa fa-certificate"></span> {% trans "Official members" %}</a></li>
{% endblock %}

{% block nav_right_items %}{# Visitor menu #}

{% if not user.is_authenticated %}
<li class="nav-item"><a href="{% url 'signon:login' %}"><span class="fa fa-sign-in"></span> {% trans "Login" %}</a></li>
{% else %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="fa fa-user-circle"></span>
    {{user.username}}
  </a>
  <div class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="navbarDropdown">
  {% block visitor_menu %}
    {% if request.impersonator %}
    <form class="form-inline" method="POST" action="{% url 'impersonate:impersonate' %}">{% csrf_token %}
      <input type="hidden" name="next" value="{{request.build_absolute_uri}}">
      <button class="dropdown-item btn btn-link" type="submit"><span class="fa fa-random"></span> (really {{request.impersonator}})</button>
    </form>
    {% endif %}
    <a class="dropdown-item" href="{{user.get_absolute_url}}"><span class="fa fa-user"></span> {% trans "Personal page" %}</a>
    <a class="dropdown-item" href="{% url 'claim:claim' %}"><span class="fa fa-user-plus"></span> {% trans "Associate identifiers" %}</a>
    <a class="dropdown-item" href="{% url 'signon:login' %}"><span class="fa fa-sign-in"></span> {% trans "Logins" %}</a>
    <form class="form-inline" method="POST" action="{% url "signon:logout" %}">{% csrf_token %}
      <input type="hidden" name="next" value="{% url 'contributors' %}">
      <button class="btn btn-link dropdown-item" method="submit"><span class="fa fa-sign-out"></span> {% trans "Logout" %}</button>
    </form>
  {% endblock %}
  </div>
</li>
{% endif %}

{% endblock %}

{% block content %}
<h1>Debian Contributors Website Template</h1>
{% endblock %}

{% block page_lead %}
{{super}}
{% if user.impersonator %}
<div id="impersonation" class="container-fluid bg-warning">
<span class="badge badge-pill badge-light"><span class="fa fa-random"></span> {{user.impersonator.a_link}} as {{visitor.a_link}}</span>
<form class="form-inline" method="POST" action="{% url 'impersonate:impersonate' %}">{% csrf_token %}
  <input type="hidden" name="next" value="{{request.build_absolute_uri}}">
  <button class="badge badge-pill badge-primary" type="submit">{% trans "Cancel" %}</button>
</form>
<br>
{% for perm in visit_perms %}<span class="badge badge-pill badge-info mr-1">{{perm}}</span>{% endfor %}
</div>
{% endif %}

{# {% if messages %} #}
<div aria-live="polite" aria-atomic="true" style="position: relative">
  <div style="position: absolute; top: 0; right: 0;">
    {% for message in messages %}
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <span class="fa fa-{% if message.level_tag == 'info' %}info-circle{% else %}warning{% endif %} mr-1"></span>
        <strong class="mr-auto">{{message.level_tag}}</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        {{message}}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{# {% endif %} #}
{% endblock %}


{% block footer %}
<div class="card-body">
{% url 'root_license' as root_license_url %}
<p class="card-text"><small>
{% blocktrans with root_license_url=root_license_url %}
<a href="{{root_license_url}}">Copyright</a> © 2012--2024 <a href="https://wiki.debian.org/Teams/FrontDesk">Debian Front Desk</a>.
Source code is <a href="https://salsa.debian.org/nm-team/contributors.debian.org">available on Salsa</a>
Report bugs on <a href="https://salsa.debian.org/nm-team/contributors.debian.org/-/issues">Salsa</a> or on the <a href="http://bugs.debian.org/nm.debian.org">Debian BTS</a>.
{% endblocktrans %}
</small>
</p>
</div>
{% endblock %}

dclayout/templates/license.html
{% extends "dc-base.html" %}

{% block content %}

<div id="intro">
    <p>This page shows details about the license of the website.</p>
</div>

<p>This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.</p>

<p>This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.</p>

<p>You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see
<a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>.</p>

{% endblock %}

dclayout/templates/privacy.html
{% extends "dc-base.html" %}

{% block content %}

<div id="intro">
    <p>This page describes the Debian Contributors website from a privacy point of view.</p>
</div>

Current opt-in/opt-out situation:

opt-out:
 * Contributions done with a @debian.org or @users.alioth.debian.org login or email address
 * Contributions done with an OpenPGP key that is in a DD or DM keyring
 * Contributions done with an email address that is in a well-signed UID in the DD or DM keyring

opt-in: anything else

Identity management features:
 * You can set your display name to anything you identify with.
 * You can hide all your contributions, no matter what.
 * You can hide all contributions done under any email addresses, login names
   or OpenPGP key that you do not want to be publicly visible.
 * You can hide your activity in any team where you do not want to be visible.

Visibility features:
 - your identifiers are visible only by yourself when you are logged in. The
   site will never publish your email addresses, or gpg key fingerprints except
   the @debian.org and @users.alioth.debian.org that it uses as usernames.
    - exception: if you go to https://contributors.debian.org/contributor/enrico@enricozini.org
      it will recognise any known identifier and map it to your main identity.
      That feature is needed to provide links to your contributors page from
      DDPO, the PTS and other Debian pages.

Not implemented yet:
 - taking ownership of an email address, gpg key or account name that has not
   been automatically assigned to your debian or alioth account. It will be
   implemented soon, but if in the meantime there is some activity you want to
   opt-out, please send an email to enrico@debian.org and it'll be done
   manually and confidentially.


{% endblock %}