claim/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "claim"

urlpatterns = [
    path('', views.Claim.as_view(), name="claim"),
    path('<username>/', views.ClaimUser.as_view(), name="menu"),
    path('<username>/email/', views.ClaimEmail.as_view(), name="email"),
    path('<username>/login/', views.ClaimLogin.as_view(), name="login"),
    path('<username>/fpr/', views.ClaimFingerprint.as_view(), name="fpr"),
    path('<username>/email/verify', views.ClaimEmailVerify.as_view(), name="verify_email"),
    path('<username>/unclaim/', views.UnclaimMenu.as_view(), name="unclaim_menu"),
    path('<username>/unclaim/<int:ident>/', views.Unclaim.as_view(), name="unclaim"),
    # path('<name>/unclaim/', views.Unclaim.as_view(), name="unclaim"),
]

contributor/urls.py
from django.urls import path
from . import views

app_name = "contributor"

urlpatterns = [
    path('<name>/', views.ContributorView.as_view(), name='detail'),
    path('<name>/save_settings/', views.SaveSettings.as_view(), name="save_settings"),
]

contributors/urls.py
from __future__ import annotations
from django.urls import path
from importer import views as iviews
from . import views

urlpatterns = [
    path('year/<int:year>', views.Contributors.as_view(), name="contributors_year"),
    path('post', iviews.PostSourceView.as_view(), name="contributors_post"),
    path('test_post', iviews.TestPostSourceView.as_view(), name="contributors_test_post"),
    path('flat', views.ContributorsFlat.as_view(), name="contributors_flat"),
    path('new', views.ContributorsNew.as_view(), name="contributors_new"),
    path('mia', views.ContributorsMIA.as_view(), name="contributors_mia"),
    path('mia/query', views.MIAQuery.as_view(), name="contributors_mia_query"),
    path('sources/flat', views.SourcesFlat.as_view(), name="contributors_sources_flat"),
    path('export/sources', iviews.ExportSources.as_view(), name="contributors_export_sources"),
    path('site_status', views.SiteStatus.as_view(), name="site_status"),
    path('test_messages', views.TestMessages.as_view(), name="test_messages"),
    path('export/public', iviews.ExportDB.as_view(), name="contributors_export_public"),
]

dc/urls.py
from __future__ import annotations
from django.urls import include, path
from django.views.generic import TemplateView
import django.conf.urls
from contributors import views as cviews
import dclayout.views as dcviews
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'contributors', cviews.ContributorViewSet, "contributors")
router.register(r'identifiers', cviews.IdentifierViewSet, "identifiers")

django.conf.urls.handler403 = dcviews.Error403.as_view()
django.conf.urls.handler404 = dcviews.Error404.as_view()
django.conf.urls.handler500 = dcviews.Error500.as_view()


urlpatterns = [
    path('', cviews.Contributors.as_view(), name="contributors"),
    path('license/', TemplateView.as_view(template_name='license.html'), name="root_license"),
    path('about/privacy/', TemplateView.as_view(template_name='privacy.html'), name="root_privacy"),
    path('admin/', admin.site.urls),
    path('contributors/', include('contributors.urls')),
    path('contributor/', include('contributor.urls')),
    path('source/', include("sources.urls")),
    path('mia/', include("mia.urls")),
    path('importer/', include("importer.urls")),
    path('claim/', include("claim.urls")),
    path('api/', include(router.urls)),
    path('deploy/', include("deploy.urls")),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),
]

impersonate/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "impersonate"

urlpatterns = [
    # Impersonate a user
    path('impersonate/', views.Impersonate.as_view(), name="impersonate"),
    path('whoami/', views.Whoami.as_view(), name="whoami"),
]

sources/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "sources"

urlpatterns = [
    path('', views.SourcesList.as_view(), name="list"),
    path('add/', views.SourceCreate.as_view(), name='add'),
    path('<sname>/', views.SourceView.as_view(), name='view'),
    path('<sname>/ctype/<name>/', views.CtypeView.as_view(), name='ctype_view'),
    path('<sname>/update/', views.SourceUpdate.as_view(), name='update'),
    path('<sname>/delete/', views.SourceDelete.as_view(), name='delete'),
    path('<sname>/delete/contributions/', views.SourceDeleteContributions.as_view(), name='delete_contributions'),
    path('<sname>/backups/', views.SourceBackupList.as_view(), name='backup_list'),
    path('<sname>/backups/<int:backup_id>/', views.SourceBackupDownload.as_view(), name='backup_download'),
    path('<sname>/members/', views.SourceMembers.as_view(), name='members'),
    path('<sname>/members/add/', views.SourceMembersAdd.as_view(), name='members_add'),
    path('<sname>/members/delete/', views.SourceMembersDelete.as_view(), name='members_delete'),
    path('<sname>/ctypes/add/', views.ContributionTypeCreate.as_view(), name='ctype_add'),
    path('<sname>/ctype/<name>/update/', views.ContributionTypeUpdate.as_view(), name='ctype_update'),
    path('<sname>/ctype/<name>/delete/', views.ContributionTypeDelete.as_view(), name='ctype_delete'),
    path('<sname>/ctype/<name>/delete/contributions/', views.ContributionTypeDeleteContributions.as_view(),
         name='ctype_delete_contributions'),
    path('<sname>/user-settings/', views.SourceUserSettings.as_view(), name='user_settings'),
]

contributor/models.py
from django.db import models

# Create your models here.

contributor/views.py
from django import http
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import DetailView, View
from contributors import models as cmodels
from django.utils.translation import gettext as _
from dc.mixins import VisitorMixin
from signon.models import Identity


class ContributorMixin(VisitorMixin):
    def load_objects(self):
        super().load_objects()
        name = self.kwargs["name"]
        try:
            self.contributor = cmodels.User.objects.get(username=name)
        except cmodels.User.DoesNotExist:
            self.contributor = None

        if self.contributor is None:
            if name.endswith("@alioth"):
                identity = get_object_or_404(Identity, issuer="debsso", subject=f"{name[:-7]}@users.alioth.debian.org")
            elif name.endswith("@debian"):
                identity = get_object_or_404(Identity, issuer="debsso", subject=f"{name[:-7]}@debian.org")
            elif name.endswith("@salsa"):
                identity = get_object_or_404(Identity, issuer="salsa", username=f"{name[:-6]}")
            else:
                identity = None

            if identity is None or identity.person is None:
                identifier = cmodels.Identifier.objects.filter(name=name).first()

                if identifier is None or identifier.user is None:
                    raise http.Http404("No contributor found")
                return redirect(identifier.user, permanent=True)
            else:
                self.contributor = identity.person

        self.own_page = (
                self.contributor is not None
                and (self.request.user.is_superuser or self.request.user == self.contributor))

        # Someone else is visting this user: enforce visibility settings
        if self.contributor is not None and self.contributor.hidden and not self.own_page:
            self.contributor = None

        if self.contributor is None:
            raise http.Http404(_("No contributor found matching the query"))

    def check_visitor_permission(self, perm):
        if perm == "own_page":
            return self.own_page
        else:
            return super(ContributorMixin, self).check_visitor_permission(perm)

    def get_object(self):
        return self.contributor

    def get_context_data(self, **kw):
        ctx = super(ContributorMixin, self).get_context_data(**kw)
        ctx["contributor"] = self.contributor
        ctx["own_page"] = self.own_page
        return ctx


class ContributorView(ContributorMixin, DetailView):
    template_name = "contributor/contributor.html"
    context_object_name = 'contributor'

    def get_context_data(self, **kw):
        context = super().get_context_data(**kw)

        if self.own_page:
            context["user_log"] = list(self.object.log.order_by("-ts"))
            source_settings = cmodels.UserSourceSettings.objects.filter(user=self.object, hidden=True).distinct()
            identifiers = []
            for ident in self.object.identifiers.order_by("type", "name"):
                identifiers.append({
                    "ident": ident,
                    "log": ident.log.order_by("-ts"),
                })
            context["identifiers"] = identifiers
            context["source_settings"] = list(source_settings)
            context["hide_user"] = self.object.hidden

        contributions = []
        for c in self.object.contributions().order_by("identifier"):
            if self.own_page or not c.hidden:
                contributions.append(c)

        context["contributions"] = contributions
        context['redacted'] = not self.own_page
        return context


class SaveSettings(ContributorMixin, View):
    require_visitor = "own_page"

    def post(self, request, *args, **kw):
        changed = False

        # Updated user info
        full_name = self.request.POST.get("full_name", "")
        if full_name != self.contributor.full_name:
            self.contributor.full_name = full_name
            self.contributor.save()

        # Update user visibility
        want_hidden_user = bool(request.POST.get("hide_user", False))
        if self.contributor.hidden != want_hidden_user:
            self.contributor.hidden = want_hidden_user
            self.contributor.save()
            changed = True

        # Update identifier visibility
        for ident in self.contributor.identifiers.all():
            want_hidden = bool(self.request.POST.get("hide_{}".format(ident.pk), False))
            if ident.hidden != want_hidden:
                ident.hidden = want_hidden
                ident.save()
                changed = True

        if changed:
            cmodels.AggregatedPersonContribution.recompute(user=self.contributor)
            cmodels.AggregatedSource.recompute()
            cmodels.AggregatedPerson.recompute(user=self.contributor)

        return redirect(self.contributor.get_absolute_url())

contributor/templates/contributor/base.html
{% extends "dc-base.html" %}

{% block content %}
<h1>Debian Contributors Page Template</h1>
{% endblock %}

contributor/templates/contributor/contributor.html
{% extends "contributors/base.html" %}
{% load i18n %}

{% block head %}
{{block.super}}
<style>
.errorlist {
  color: red;
}
td.save_settings {
  text-align: right;
}
p.visform {
  margin: 0;
}
p.visuser {
  margin-bottom: 1em;
}
p.vissubmit {
  margin-top: 1em;
}
tr.hidden {
  background: #ccc;
}
</style>
{% endblock %}

{% block nav_left_items %}
{{block.super}}
{% if contributor and contributor != request.user %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="fa fa-user-circle"></span>
    {{contributor.username}}
  </a>
  <div class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="navbarDropdown">
    {% if request.user.is_superuser %}
    <form class="form-inline" method="POST" action="{% url 'impersonate:impersonate' %}">{% csrf_token %}
      <input type="hidden" name="pk" value="{{contributor.pk}}">
      <input type="hidden" name="next" value="{{request.build_absolute_uri}}">
      <button class="dropdown-item btn btn-link" type="submit"><span class="fa fa-random"></span> {% trans "Impersonate" %}</button>
    </form>
    {% endif %}
    <a class="dropdown-item" href="{{contributor.get_absolute_url}}"><span class="fa fa-user"></span> {% trans "Personal page" %}</a>
    {% if request.user.is_dd %}
    <a class="dropdown-item" href="{% url 'claim:menu' contributor.username %}"><span class="fa fa-user-plus"></span> {% trans "Associate identifiers" %}</a>
    {% endif %}
{% comment %}
    {% if not redacted or request.user.is_dd %}<a class="dropdown-item" href="{% url 'contributor:unclaim' name=contributor.username %}"><span class="fa fa-user-times"></span> Unassociate identifiers</a>{% endif %}
{% endcomment %}
  </div>
</li>
{% endif %}
{% endblock %}

{% block content %}

<div class="container-fluid">

{% if contributor.is_dd %}
<div class="badge badge-pill badge-primary float-right">Debian Developer</div>
{% endif %}

<h1 class="d-flex">
  {% with contributor.get_picture_url as picture %}
    {% if picture %}
    <img class="mr-2 personpic" src="{{picture}}"></img>
    {% endif %}
  {% endwith %}
  {{contributor.full_name}}
</h1>

<p class="lead">
  {% if redacted %}
  <i>{{contributor}}</i> has contributed to:
  {% else %}
  You have contributed to:
  {% endif %}
</p>

<table class="table table-sm tablesorter">
<thead>
  <tr>
    <th>{% trans "Identifier" %}</th>
    <th>{% trans "Team" %}</th>
    <th>{% trans "Contribution" %}</th>
    <th>{% trans "Since" %}</th>
    <th>{% trans "Until" %}</th>
  </tr>
</thead>
<tbody>
{% for c in contributions %}
<tr {% if c.hidden %}class="hidden"{% endif %}>
      {% if redacted %}
      <td>
        {{c.identifier.type}}:{% if c.identifier.type == "email" %}hidden{% else %}{{c.identifier.name}}{% endif %}
      </td>
      {% else %}
      <td>{{c.identifier.type}}:{{c.identifier.name}}</td>
      {% endif %}
      <td>
        <a href="{{c.type.source.get_absolute_url}}">{{c.type.source}}</a>
      </td>
      <td>
        <a href="{{c.type.get_absolute_url}}">{{c.type.contrib_desc}}</a>
        {% if c.url %}
        <a href="{{c.url}}">(extra info)</a>
        {% endif %}
      </td>
      {% if redacted %}
      <td data-sort="{{c.begin|date:"Ym"}}">{{c.begin|date:"F Y"}}</td>
      <td data-sort="{{c.until|date:"Ym"}}">{{c.until|date:"F Y"}}</td>
      {% else %}
      <td data-sort="{{c.begin|date:"Ymd"}}">{{c.begin}}</td>
      <td data-sort="{{c.until|date:"Ymd"}}">{{c.until}}</td>
      {% endif %}
    </tr>
{% endfor %}
</tbody>
</table>

{% if not redacted %}

<h2 class="mt-3">{% trans "Activity logs" %}</h2>

<div class="row">
  <div class="col-3 overflow-hidden">
    <div class="nav flex-column nav-pills" id="logs-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="logs-user-tab" data-toggle="pill" href="#logs-user" role="tab" aria-controls="logs-user" aria-selected="true">
        <span class="fa fa-user-circle"></span>
        {% trans 'User' %}
      </a>
      {% for s in identifiers %}
      <a class="nav-link text-nowrap" id="logs-ident-{{s.ident.pk}}-tab" data-toggle="pill" href="#logs-ident-{{s.ident.pk}}" role="tab" aria-controls="logs-ident-{{s.ident.pk}}" aria-selected="false">
        {% if s.ident.type == "email" %}
        <span class="fa fa-at"></span>
        {% elif s.ident.type == "fpr" %}
        <span class="fa fa-gnupg"></span>
        {% elif s.ident.type == "login" %}
        <span class="fa fa-user"></span>
        {% else %}
        <span class="fa fa-chevron-circle-right"></span>
        {% endif %}
        {{s.ident.name}}
      </a>
      {% endfor %}
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="logs-tabcontent">
      <div class="tab-pane show active" id="logs-user-tab" role="tabpanel" aria-labelledby="logs-user-tab">
        {% if user_log %}
        <h2>{% trans "User activity log" %}</h2>
        <table class="table table-sm tablesorter">
          <thead>
            <tr><th>{% trans "Time" %}</th><th>{% trans "Entry" %}</th></tr>
          </thead>
          <tbody>
          {% for l in user_log %}
            <tr><td data-sort="{{l.ts|date:"YmdHis"}}">{{l.ts}}</td><td>{{l.text}}</td></tr>
          {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>{% trans "No activity found on record." %}</p>
        {% endif %}
      </div>
      {% for s in identifiers %}
      <div class="tab-pane" id="logs-ident-{{s.ident.pk}}" role="tabpanel" aria-labelledby="logs-ident-{{s.ident.pk}}-tab">
        {% if s.log %}
	<h2>{% blocktrans with name=s.ident.name %}Activity log for {{name}}{% endblocktrans %}</h2>
        <table class="tablesorter">
          <thead>
            <tr><th>{% trans "Time" %}</th><th>{% trans "Entry" %}</th></tr>
          </thead>
          <tbody>
          {% for l in s.log %}
            <tr><td data-sort="{{l.ts|date:"YmdHis"}}">{{l.ts}}</td><td>{{l.text}}</td></tr>
          {% endfor %}
          </tbody>
        </table>
        {% else %}
        {% trans "No activity found on record." %}
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<h2 class="mt-3">{% trans "Settings" %}</h2>

<form method="post" action="{% url 'contributor:save_settings' name=contributor.username %}">{% csrf_token %}

<h3>{% trans "User information" %}</h3>

<div class="form-group">
<label for="full_name">{% trans "Full name: " %}</label>
<input class="form-control" type="text" name="full_name" value="{{contributor.full_name}}"></input>
</div>

<h3>{% trans "User visibility" %}</h3>

<div class="form-group form-check visform visuser">
<input type="checkbox" name="hide_user" {% if hide_user %}checked{% endif %} class="hide_user form-check-input">
<label class="form-check-label" for="hide_user">{% trans "hide all activity from this user" %}</label>
</div>

{% for s in identifiers %}
<div class="form-group form-check visform">
<input type="checkbox" name="hide_{{s.ident.pk}}" {% if s.ident.hidden %}checked{% endif %} class="hide_ident form-check-input">
<label class="form-check-label" for="hide_{{s.ident.pk}}">
  {% blocktrans with type=s.ident.type name=s.ident.name %}
  hide all activity from {{type}} "{{name}}"
  {% endblocktrans %}
</label>
</div>

<a class="btn btn-warning" href="{% url 'claim:unclaim' username=user.username ident=s.ident.pk %}">{% trans "Disassociate" %} {{s.ident.name}}</a>
{% endfor %}

<button class="btn btn-primary visform vissubmit">{% trans "Save settings" %}</button>

</form>

<h3 class="mt-3">{% trans "Hidden contributions" %}</h3>

{% if source_settings %}
<p>{% trans "These teams are currently hidden:" %}</p>
<ul>
  {% for s in source_settings %}
  <li>
    You will not show in team <a href="{% url 'sources:user_settings' sname=s.source.name %}">{{s.source.name}}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>{% trans "No teams are currently hidden." %}</p>
{% endif %}

{% endif %}

</div>

{% endblock %}

contributor/templates/contributor/unclaim.html
{% extends "contributors/base.html" %}
{% load i18n %}

{% block content %}

<h1>Debian Contributor {{contributor}}: unassociate identifiers</h1>

<div id="intro">
  {% if own_page %}
  From this page you can unassociate some of the identifiers currently associated with you.
  {% else %}
  From this page you can unassociate some of the identifiers currently associated with {{contributor}}.
  {% endif %}
</div>

<table class="tablesorter">
<thead>
  <tr>
    <th>{% trans "Type" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Actions" %}</th>
  </tr>
</thead>
<tbody>
{% for ident in identifiers %}
<tr>
  <td>{{ident.type}}</td>
  <td>{{ident.name}}</td>
  <td>
    <form action="{% url 'contributor:unclaim' name=contributor.username %}" method="POST">{% csrf_token %}
      <button name="id" value="{{ident.pk}}">Unassociate</button>
    </form>
  </td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock %}